"""
Pinterest connector for Airbyte SDK.

Auto-generated from OpenAPI specification.
"""

from .connector import PinterestConnector
from .models import (
    PinterestAuthConfig,
    PinterestReplicationConfig,
    AirbyteSearchMeta,
    AirbyteSearchResult,
    AdAccountsSearchData,
    AdAccountsSearchResult,
    BoardsSearchData,
    BoardsSearchResult,
    CampaignsSearchData,
    CampaignsSearchResult,
    AdGroupsSearchData,
    AdGroupsSearchResult,
    AdsSearchData,
    AdsSearchResult,
    BoardSectionsSearchData,
    BoardSectionsSearchResult,
    BoardPinsSearchData,
    BoardPinsSearchResult,
    CatalogsSearchData,
    CatalogsSearchResult,
    CatalogsFeedsSearchData,
    CatalogsFeedsSearchResult,
    CatalogsProductGroupsSearchData,
    CatalogsProductGroupsSearchResult,
    AudiencesSearchData,
    AudiencesSearchResult,
    ConversionTagsSearchData,
    ConversionTagsSearchResult,
    CustomerListsSearchData,
    CustomerListsSearchResult,
    KeywordsSearchData,
    KeywordsSearchResult,
)
from airbyte_agent_sdk.types import AirbyteAuthConfig

__all__ = [
    "PinterestConnector",
    "AirbyteAuthConfig",
    "PinterestAuthConfig",
    "PinterestReplicationConfig",
    "AirbyteSearchMeta",
    "AirbyteSearchResult",
    "AdAccountsSearchData",
    "AdAccountsSearchResult",
    "BoardsSearchData",
    "BoardsSearchResult",
    "CampaignsSearchData",
    "CampaignsSearchResult",
    "AdGroupsSearchData",
    "AdGroupsSearchResult",
    "AdsSearchData",
    "AdsSearchResult",
    "BoardSectionsSearchData",
    "BoardSectionsSearchResult",
    "BoardPinsSearchData",
    "BoardPinsSearchResult",
    "CatalogsSearchData",
    "CatalogsSearchResult",
    "CatalogsFeedsSearchData",
    "CatalogsFeedsSearchResult",
    "CatalogsProductGroupsSearchData",
    "CatalogsProductGroupsSearchResult",
    "AudiencesSearchData",
    "AudiencesSearchResult",
    "ConversionTagsSearchData",
    "ConversionTagsSearchResult",
    "CustomerListsSearchData",
    "CustomerListsSearchResult",
    "KeywordsSearchData",
    "KeywordsSearchResult",
]