"""
Woocommerce connector for Airbyte SDK.

Auto-generated from OpenAPI specification.
"""

from .connector import WoocommerceConnector
from .models import (
    WoocommerceAuthConfig,
    WoocommerceReplicationConfig,
    AirbyteSearchMeta,
    AirbyteSearchResult,
    CustomersSearchData,
    CustomersSearchResult,
    OrdersSearchData,
    OrdersSearchResult,
    ProductsSearchData,
    ProductsSearchResult,
    CouponsSearchData,
    CouponsSearchResult,
    ProductCategoriesSearchData,
    ProductCategoriesSearchResult,
    ProductTagsSearchData,
    ProductTagsSearchResult,
    ProductReviewsSearchData,
    ProductReviewsSearchResult,
    ProductAttributesSearchData,
    ProductAttributesSearchResult,
    ProductVariationsSearchData,
    ProductVariationsSearchResult,
    OrderNotesSearchData,
    OrderNotesSearchResult,
    RefundsSearchData,
    RefundsSearchResult,
    PaymentGatewaysSearchData,
    PaymentGatewaysSearchResult,
    ShippingMethodsSearchData,
    ShippingMethodsSearchResult,
    ShippingZonesSearchData,
    ShippingZonesSearchResult,
    TaxRatesSearchData,
    TaxRatesSearchResult,
    TaxClassesSearchData,
    TaxClassesSearchResult,
)
from airbyte_agent_sdk.types import AirbyteAuthConfig

__all__ = [
    "WoocommerceConnector",
    "AirbyteAuthConfig",
    "WoocommerceAuthConfig",
    "WoocommerceReplicationConfig",
    "AirbyteSearchMeta",
    "AirbyteSearchResult",
    "CustomersSearchData",
    "CustomersSearchResult",
    "OrdersSearchData",
    "OrdersSearchResult",
    "ProductsSearchData",
    "ProductsSearchResult",
    "CouponsSearchData",
    "CouponsSearchResult",
    "ProductCategoriesSearchData",
    "ProductCategoriesSearchResult",
    "ProductTagsSearchData",
    "ProductTagsSearchResult",
    "ProductReviewsSearchData",
    "ProductReviewsSearchResult",
    "ProductAttributesSearchData",
    "ProductAttributesSearchResult",
    "ProductVariationsSearchData",
    "ProductVariationsSearchResult",
    "OrderNotesSearchData",
    "OrderNotesSearchResult",
    "RefundsSearchData",
    "RefundsSearchResult",
    "PaymentGatewaysSearchData",
    "PaymentGatewaysSearchResult",
    "ShippingMethodsSearchData",
    "ShippingMethodsSearchResult",
    "ShippingZonesSearchData",
    "ShippingZonesSearchResult",
    "TaxRatesSearchData",
    "TaxRatesSearchResult",
    "TaxClassesSearchData",
    "TaxClassesSearchResult",
]