"""Type stubs for connect(): per-connector Literal overloads.

Auto-generated by airbyte_agent_sdk.codegen.generator.write_connect_stub(). Do not edit by hand.
"""

from typing import Literal, overload

from airbyte_agent_sdk.executor.hosted_executor import HostedExecutor
from airbyte_agent_sdk.types import AirbyteAuthConfig
from airbyte_agent_sdk.connectors.airtable import AirtableConnector
from airbyte_agent_sdk.connectors.amazon_ads import AmazonAdsConnector
from airbyte_agent_sdk.connectors.amazon_seller_partner import AmazonSellerPartnerConnector
from airbyte_agent_sdk.connectors.amplitude import AmplitudeConnector
from airbyte_agent_sdk.connectors.asana import AsanaConnector
from airbyte_agent_sdk.connectors.ashby import AshbyConnector
from airbyte_agent_sdk.connectors.chargebee import ChargebeeConnector
from airbyte_agent_sdk.connectors.clickup_api import ClickupApiConnector
from airbyte_agent_sdk.connectors.confluence import ConfluenceConnector
from airbyte_agent_sdk.connectors.customer_io import CustomerIoConnector
from airbyte_agent_sdk.connectors.exa import ExaConnector
from airbyte_agent_sdk.connectors.facebook_marketing import FacebookMarketingConnector
from airbyte_agent_sdk.connectors.freshdesk import FreshdeskConnector
from airbyte_agent_sdk.connectors.github import GithubConnector
from airbyte_agent_sdk.connectors.gitlab import GitlabConnector
from airbyte_agent_sdk.connectors.gmail import GmailConnector
from airbyte_agent_sdk.connectors.gong import GongConnector
from airbyte_agent_sdk.connectors.google_ads import GoogleAdsConnector
from airbyte_agent_sdk.connectors.google_analytics_data_api import GoogleAnalyticsDataApiConnector
from airbyte_agent_sdk.connectors.google_drive import GoogleDriveConnector
from airbyte_agent_sdk.connectors.google_search_console import GoogleSearchConsoleConnector
from airbyte_agent_sdk.connectors.granola import GranolaConnector
from airbyte_agent_sdk.connectors.greenhouse import GreenhouseConnector
from airbyte_agent_sdk.connectors.harvest import HarvestConnector
from airbyte_agent_sdk.connectors.hubspot import HubspotConnector
from airbyte_agent_sdk.connectors.incident_io import IncidentIoConnector
from airbyte_agent_sdk.connectors.intercom import IntercomConnector
from airbyte_agent_sdk.connectors.jira import JiraConnector
from airbyte_agent_sdk.connectors.klaviyo import KlaviyoConnector
from airbyte_agent_sdk.connectors.linear import LinearConnector
from airbyte_agent_sdk.connectors.linkedin_ads import LinkedinAdsConnector
from airbyte_agent_sdk.connectors.mailchimp import MailchimpConnector
from airbyte_agent_sdk.connectors.monday import MondayConnector
from airbyte_agent_sdk.connectors.notion import NotionConnector
from airbyte_agent_sdk.connectors.orb import OrbConnector
from airbyte_agent_sdk.connectors.paypal_transaction import PaypalTransactionConnector
from airbyte_agent_sdk.connectors.pinterest import PinterestConnector
from airbyte_agent_sdk.connectors.pylon import PylonConnector
from airbyte_agent_sdk.connectors.salesforce import SalesforceConnector
from airbyte_agent_sdk.connectors.sendgrid import SendgridConnector
from airbyte_agent_sdk.connectors.sentry import SentryConnector
from airbyte_agent_sdk.connectors.shopify import ShopifyConnector
from airbyte_agent_sdk.connectors.slack import SlackConnector
from airbyte_agent_sdk.connectors.snapchat_marketing import SnapchatMarketingConnector
from airbyte_agent_sdk.connectors.snowflake import SnowflakeConnector
from airbyte_agent_sdk.connectors.stripe import StripeConnector
from airbyte_agent_sdk.connectors.tiktok_marketing import TiktokMarketingConnector
from airbyte_agent_sdk.connectors.twilio import TwilioConnector
from airbyte_agent_sdk.connectors.typeform import TypeformConnector
from airbyte_agent_sdk.connectors.woocommerce import WoocommerceConnector
from airbyte_agent_sdk.connectors.zendesk_chat import ZendeskChatConnector
from airbyte_agent_sdk.connectors.zendesk_support import ZendeskSupportConnector
from airbyte_agent_sdk.connectors.zendesk_talk import ZendeskTalkConnector
from airbyte_agent_sdk.connectors.zoho_crm import ZohoCrmConnector

@overload
def connect(
    connector_name: Literal["airtable"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> AirtableConnector: ...


@overload
def connect(
    connector_name: Literal["amazon-ads"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> AmazonAdsConnector: ...


@overload
def connect(
    connector_name: Literal["amazon-seller-partner"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> AmazonSellerPartnerConnector: ...


@overload
def connect(
    connector_name: Literal["amplitude"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> AmplitudeConnector: ...


@overload
def connect(
    connector_name: Literal["asana"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> AsanaConnector: ...


@overload
def connect(
    connector_name: Literal["ashby"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> AshbyConnector: ...


@overload
def connect(
    connector_name: Literal["chargebee"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> ChargebeeConnector: ...


@overload
def connect(
    connector_name: Literal["clickup-api"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> ClickupApiConnector: ...


@overload
def connect(
    connector_name: Literal["confluence"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> ConfluenceConnector: ...


@overload
def connect(
    connector_name: Literal["customer-io"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> CustomerIoConnector: ...


@overload
def connect(
    connector_name: Literal["exa"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> ExaConnector: ...


@overload
def connect(
    connector_name: Literal["facebook-marketing"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> FacebookMarketingConnector: ...


@overload
def connect(
    connector_name: Literal["freshdesk"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> FreshdeskConnector: ...


@overload
def connect(
    connector_name: Literal["github"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> GithubConnector: ...


@overload
def connect(
    connector_name: Literal["gitlab"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> GitlabConnector: ...


@overload
def connect(
    connector_name: Literal["gmail"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> GmailConnector: ...


@overload
def connect(
    connector_name: Literal["gong"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> GongConnector: ...


@overload
def connect(
    connector_name: Literal["google-ads"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> GoogleAdsConnector: ...


@overload
def connect(
    connector_name: Literal["google-analytics-data-api"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> GoogleAnalyticsDataApiConnector: ...


@overload
def connect(
    connector_name: Literal["google-drive"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> GoogleDriveConnector: ...


@overload
def connect(
    connector_name: Literal["google-search-console"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> GoogleSearchConsoleConnector: ...


@overload
def connect(
    connector_name: Literal["granola"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> GranolaConnector: ...


@overload
def connect(
    connector_name: Literal["greenhouse"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> GreenhouseConnector: ...


@overload
def connect(
    connector_name: Literal["harvest"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> HarvestConnector: ...


@overload
def connect(
    connector_name: Literal["hubspot"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> HubspotConnector: ...


@overload
def connect(
    connector_name: Literal["incident-io"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> IncidentIoConnector: ...


@overload
def connect(
    connector_name: Literal["intercom"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> IntercomConnector: ...


@overload
def connect(
    connector_name: Literal["jira"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> JiraConnector: ...


@overload
def connect(
    connector_name: Literal["klaviyo"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> KlaviyoConnector: ...


@overload
def connect(
    connector_name: Literal["linear"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> LinearConnector: ...


@overload
def connect(
    connector_name: Literal["linkedin-ads"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> LinkedinAdsConnector: ...


@overload
def connect(
    connector_name: Literal["mailchimp"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> MailchimpConnector: ...


@overload
def connect(
    connector_name: Literal["monday"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> MondayConnector: ...


@overload
def connect(
    connector_name: Literal["notion"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> NotionConnector: ...


@overload
def connect(
    connector_name: Literal["orb"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> OrbConnector: ...


@overload
def connect(
    connector_name: Literal["paypal-transaction"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> PaypalTransactionConnector: ...


@overload
def connect(
    connector_name: Literal["pinterest"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> PinterestConnector: ...


@overload
def connect(
    connector_name: Literal["pylon"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> PylonConnector: ...


@overload
def connect(
    connector_name: Literal["salesforce"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> SalesforceConnector: ...


@overload
def connect(
    connector_name: Literal["sendgrid"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> SendgridConnector: ...


@overload
def connect(
    connector_name: Literal["sentry"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> SentryConnector: ...


@overload
def connect(
    connector_name: Literal["shopify"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> ShopifyConnector: ...


@overload
def connect(
    connector_name: Literal["slack"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> SlackConnector: ...


@overload
def connect(
    connector_name: Literal["snapchat-marketing"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> SnapchatMarketingConnector: ...


@overload
def connect(
    connector_name: Literal["snowflake"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> SnowflakeConnector: ...


@overload
def connect(
    connector_name: Literal["stripe"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> StripeConnector: ...


@overload
def connect(
    connector_name: Literal["tiktok-marketing"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> TiktokMarketingConnector: ...


@overload
def connect(
    connector_name: Literal["twilio"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> TwilioConnector: ...


@overload
def connect(
    connector_name: Literal["typeform"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> TypeformConnector: ...


@overload
def connect(
    connector_name: Literal["woocommerce"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> WoocommerceConnector: ...


@overload
def connect(
    connector_name: Literal["zendesk-chat"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> ZendeskChatConnector: ...


@overload
def connect(
    connector_name: Literal["zendesk-support"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> ZendeskSupportConnector: ...


@overload
def connect(
    connector_name: Literal["zendesk-talk"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> ZendeskTalkConnector: ...


@overload
def connect(
    connector_name: Literal["zoho-crm"],
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> ZohoCrmConnector: ...


@overload
def connect(
    connector_name: str,
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> HostedExecutor: ...


def connect(
    connector_name: str,
    *,
    client_id: str | None = ...,
    client_secret: str | None = ...,
    workspace_name: str | None = ...,
    connector_id: str | None = ...,
    organization_id: str | None = ...,
    auth_config: AirbyteAuthConfig | None = ...,
) -> HostedExecutor: ...