"""
Tiktok-Marketing connector for Airbyte SDK.

Auto-generated from OpenAPI specification.
"""

from .connector import TiktokMarketingConnector
from .models import (
    TiktokMarketingAuthConfig,
    TiktokMarketingReplicationConfig,
    AirbyteSearchMeta,
    AirbyteSearchResult,
    AdvertisersSearchData,
    AdvertisersSearchResult,
    CampaignsSearchData,
    CampaignsSearchResult,
    AdGroupsSearchData,
    AdGroupsSearchResult,
    AdsSearchData,
    AdsSearchResult,
    AudiencesSearchData,
    AudiencesSearchResult,
    CreativeAssetsImagesSearchData,
    CreativeAssetsImagesSearchResult,
    CreativeAssetsVideosSearchData,
    CreativeAssetsVideosSearchResult,
    SparkAdsSearchData,
    SparkAdsSearchResult,
    AdvertisersReportsDailySearchData,
    AdvertisersReportsDailySearchResult,
    CampaignsReportsDailySearchData,
    CampaignsReportsDailySearchResult,
    AdGroupsReportsDailySearchData,
    AdGroupsReportsDailySearchResult,
    AdsReportsDailySearchData,
    AdsReportsDailySearchResult,
    AdsReportsHourlySearchData,
    AdsReportsHourlySearchResult,
    AdsReportsLifetimeSearchData,
    AdsReportsLifetimeSearchResult,
)
from airbyte_agent_sdk.types import AirbyteAuthConfig

__all__ = [
    "TiktokMarketingConnector",
    "AirbyteAuthConfig",
    "TiktokMarketingAuthConfig",
    "TiktokMarketingReplicationConfig",
    "AirbyteSearchMeta",
    "AirbyteSearchResult",
    "AdvertisersSearchData",
    "AdvertisersSearchResult",
    "CampaignsSearchData",
    "CampaignsSearchResult",
    "AdGroupsSearchData",
    "AdGroupsSearchResult",
    "AdsSearchData",
    "AdsSearchResult",
    "AudiencesSearchData",
    "AudiencesSearchResult",
    "CreativeAssetsImagesSearchData",
    "CreativeAssetsImagesSearchResult",
    "CreativeAssetsVideosSearchData",
    "CreativeAssetsVideosSearchResult",
    "SparkAdsSearchData",
    "SparkAdsSearchResult",
    "AdvertisersReportsDailySearchData",
    "AdvertisersReportsDailySearchResult",
    "CampaignsReportsDailySearchData",
    "CampaignsReportsDailySearchResult",
    "AdGroupsReportsDailySearchData",
    "AdGroupsReportsDailySearchResult",
    "AdsReportsDailySearchData",
    "AdsReportsDailySearchResult",
    "AdsReportsHourlySearchData",
    "AdsReportsHourlySearchResult",
    "AdsReportsLifetimeSearchData",
    "AdsReportsLifetimeSearchResult",
]