"""
Sendgrid connector for Airbyte SDK.

Auto-generated from OpenAPI specification.
"""

from .connector import SendgridConnector
from .models import (
    SendgridAuthConfig,
    SendgridReplicationConfig,
    AirbyteSearchMeta,
    AirbyteSearchResult,
    BouncesSearchData,
    BouncesSearchResult,
    BlocksSearchData,
    BlocksSearchResult,
    CampaignsSearchData,
    CampaignsSearchResult,
    ContactsSearchData,
    ContactsSearchResult,
    GlobalSuppressionsSearchData,
    GlobalSuppressionsSearchResult,
    InvalidEmailsSearchData,
    InvalidEmailsSearchResult,
    ListsSearchData,
    ListsSearchResult,
    SegmentsSearchData,
    SegmentsSearchResult,
    SinglesendStatsSearchData,
    SinglesendStatsSearchResult,
    SinglesendsSearchData,
    SinglesendsSearchResult,
    SuppressionGroupMembersSearchData,
    SuppressionGroupMembersSearchResult,
    SuppressionGroupsSearchData,
    SuppressionGroupsSearchResult,
    TemplatesSearchData,
    TemplatesSearchResult,
)
from airbyte_agent_sdk.types import AirbyteAuthConfig

__all__ = [
    "SendgridConnector",
    "AirbyteAuthConfig",
    "SendgridAuthConfig",
    "SendgridReplicationConfig",
    "AirbyteSearchMeta",
    "AirbyteSearchResult",
    "BouncesSearchData",
    "BouncesSearchResult",
    "BlocksSearchData",
    "BlocksSearchResult",
    "CampaignsSearchData",
    "CampaignsSearchResult",
    "ContactsSearchData",
    "ContactsSearchResult",
    "GlobalSuppressionsSearchData",
    "GlobalSuppressionsSearchResult",
    "InvalidEmailsSearchData",
    "InvalidEmailsSearchResult",
    "ListsSearchData",
    "ListsSearchResult",
    "SegmentsSearchData",
    "SegmentsSearchResult",
    "SinglesendStatsSearchData",
    "SinglesendStatsSearchResult",
    "SinglesendsSearchData",
    "SinglesendsSearchResult",
    "SuppressionGroupMembersSearchData",
    "SuppressionGroupMembersSearchResult",
    "SuppressionGroupsSearchData",
    "SuppressionGroupsSearchResult",
    "TemplatesSearchData",
    "TemplatesSearchResult",
]